In [1]:
import numpy as np

In [120]:
with open("input/day10.txt", "r") as file:
    contents = file.read()
    contents = contents.translate(str.maketrans("-|F7LJ.", "─│┌┐└┘ "))

In [121]:
dane = contents.split("\n")

dane = np.array(dane).astype(str)

def findS(dane):
    for x in range(len(dane)):
        dane[x]
        for y in range(len(dane[x])):
            if dane[x][y] == "S":
                return [x,y]

S = np.array(findS(dane))
print(f'S = {S}')

S = [76 24]


In [122]:
# Wybranie kierunku 


type(S[0])
S + [1,0]

array([77, 24])

In [126]:
# dostaje obecna pozycje i kierunek, zwraca nowa pozycje i kierunek
lista_punktow_odwiedzonych = []

def move(pos: np.array, next_pos: np.array) -> int:
    ilosc_krokow =0

    # | - L J 7 F . S

    new_pos = pos + next_pos
    lista_punktow_odwiedzonych.append(new_pos)

    while dane[new_pos[0]][new_pos[1]] != "S":
        print(f'new_pos = {new_pos}')
        if dane[new_pos[0]][new_pos[1]] == "│":
            print("Jestem na │")
            if next_pos == [1,0]:
                new_pos = new_pos + [1,0]
                next_pos = [1,0]
            elif next_pos == [-1,0]:
                new_pos = new_pos + [-1,0]
                next_pos = [-1,0]
        elif dane[new_pos[0]][new_pos[1]] == "─":
            print("Jestem na ─")
            if next_pos == [0,1]:
                new_pos = new_pos + [0,1]
                next_pos = [0,1]
            elif next_pos == [0,-1]:
                new_pos = new_pos + [0,-1]
                next_pos = [0,-1]
        elif dane[new_pos[0]][new_pos[1]] == "└":
            print("Jestem na └")
            if next_pos == [1,0]:
                new_pos = new_pos + [0,1]
                next_pos = [0,1]
            elif next_pos == [0,-1]:
                new_pos = new_pos + [-1,0]
                next_pos = [-1,0]
        elif dane[new_pos[0]][new_pos[1]] == "┘":
            print("Jestem na ┘")
            if next_pos == [1,0]:
                new_pos = new_pos + [0,-1]
                next_pos = [0,-1]
            elif next_pos == [0,1]:
                new_pos = new_pos + [-1,0]
                next_pos = [-1,0]
        elif dane[new_pos[0]][new_pos[1]] == "┐":
            print("Jestem na ┐")
            if next_pos == [-1,0]:
                new_pos = new_pos + [0,-1]
                next_pos = [0,-1]
            elif next_pos == [0,1]:
                new_pos = new_pos + [1,0]
                next_pos = [1,0]
        elif dane[new_pos[0]][new_pos[1]] == "┌":
            print("Jestem na ┌")
            if next_pos == [-1,0]:
                new_pos = new_pos + [0,1]
                next_pos = [0,1]
            elif next_pos == [0,-1]:
                new_pos = new_pos + [1,0]
                next_pos = [1,0]
        elif dane[new_pos[0]][new_pos[1]] == " ":
            print("ERRROOR Jestem na  ")
            print(f'new_pos = {new_pos}')
            break
        ilosc_krokow += 1
        lista_punktow_odwiedzonych.append(new_pos)

    return ilosc_krokow
        


print(dane[S]) #= "┐"
   
np.ceil(move(S, [0,-1])/2)


['│ │┌┐┌└│─┌──┘┌┐└─┐││┌─┘┌S└┐└┐│┌┘│└└┐└─┐┌┐┌─┐└─┘└──┐┐└┘┌┐┌┐ │└┘┐┘┐│─┘┌└└──┐┌┐│└──┘┌┘└┐└┐││┌─┐│┌┐┌┐└───┐│└────┘┌┐┌───┘┌┐┌┘┌┐└──────┘└─┐┘│┌─┐─┐'
 '┌┐┌──┘│ │┘┌└ ┌┌─┐┐─└──┘┌─┘└┘┌┘└┐│││└┐│││┌┘┌┘┌┘┌┘│└─┐┌└┐┌───┘└┐┌┘│││└──┘└───┘┌┘└┐││┌─┘│││┌┘┌─┐┌─┘└─┐││││┘│┌┘││└┐└┐└┐│││┌┌┐ │ ┌└└┐┌┘┐└┘┌┌ ┌└┌┐']
new_pos = [76 23]
Jestem na ┌
new_pos = [77 23]
Jestem na ┘
new_pos = [77 22]
Jestem na ┌
new_pos = [78 22]
Jestem na ┘
new_pos = [78 21]
Jestem na └
new_pos = [77 21]
Jestem na ┐
new_pos = [77 20]
Jestem na └
new_pos = [76 20]
Jestem na ┌
new_pos = [76 21]
Jestem na ─
new_pos = [76 22]
Jestem na ┘
new_pos = [75 22]
Jestem na ┐
new_pos = [75 21]
Jestem na ─
new_pos = [75 20]
Jestem na ─
new_pos = [75 19]
Jestem na ┌
new_pos = [76 19]
Jestem na │
new_pos = [77 19]
Jestem na │
new_pos = [78 19]
Jestem na ┘
new_pos = [78 18]
Jestem na ─
new_pos = [78 17]
Jestem na ┌
new_pos = [79 17]
Jestem na ┘
new_pos = [79 16]
Jestem na ─
new_pos = [79 15]
Jestem na ─
new_pos = [79 14]
Jestem na ─
new_pos = [79 13]
Jes

6842.0

In [127]:
lista_punktow_odwiedzonych

[array([76, 23]),
 array([77, 23]),
 array([77, 22]),
 array([78, 22]),
 array([78, 21]),
 array([77, 21]),
 array([77, 20]),
 array([76, 20]),
 array([76, 21]),
 array([76, 22]),
 array([75, 22]),
 array([75, 21]),
 array([75, 20]),
 array([75, 19]),
 array([76, 19]),
 array([77, 19]),
 array([78, 19]),
 array([78, 18]),
 array([78, 17]),
 array([79, 17]),
 array([79, 16]),
 array([79, 15]),
 array([79, 14]),
 array([79, 13]),
 array([79, 12]),
 array([79, 11]),
 array([78, 11]),
 array([78, 12]),
 array([78, 13]),
 array([78, 14]),
 array([78, 15]),
 array([78, 16]),
 array([77, 16]),
 array([77, 15]),
 array([77, 14]),
 array([76, 14]),
 array([76, 13]),
 array([77, 13]),
 array([77, 12]),
 array([77, 11]),
 array([77, 10]),
 array([77,  9]),
 array([76,  9]),
 array([76, 10]),
 array([76, 11]),
 array([76, 12]),
 array([75, 12]),
 array([75, 11]),
 array([75, 10]),
 array([75,  9]),
 array([74,  9]),
 array([74, 10]),
 array([74, 11]),
 array([73, 11]),
 array([73, 12]),
 array([74

In [128]:
print(dane.shape)
print(len(dane[0]))


(140,)
140


In [156]:
# wizuazlizacja sciezki

new_array = np.zeros((140, 140), dtype=str)
for punkty in lista_punktow_odwiedzonych:
    new_array[punkty[0]][punkty[1]] = dane[punkty[0]][punkty[1]]


np.savetxt('input/output.txt', new_array, fmt='%01s', encoding='utf-8', delimiter='')

np.savetxt('input/output2.txt', dane, fmt='%s')


with open('input/output2.txt', 'w') as file:
    for row in dane:
        file.write(''.join(row) + '\n')


In [100]:
# zmienic znaki !!!!!! na 
#pipes.translate(str.maketrans("-|F7LJ.", "─│┌┐└┘ "))
# WYPRINtorwac i zajebac paintrem

In [154]:
for row in new_array:
    for i in range(len(row)):
        if row[i] == "":
            row[i] = " "

with open('input/output2.txt', 'w') as file:
    for row in new_array:
        file.write(''.join(row) + '\n')
